EXEC inserir_cliente 'Alimentos Saudáveis', 'Lisboa', 912345678, 'alimentos_saudaveis@example.com'
EXEC inserir_cliente 'FarmaNutri', 'Porto', 933333333, 'farmanutri@example.com'
EXEC inserir_cliente 'Frutaria Natural', 'Braga', 911111111, 'frutaria_natural@example.com'
EXEC inserir_cliente 'Sabor Natural', 'Coimbra', 966666666, 'sabor_natural@example.com'
EXEC inserir_cliente 'Produtos Biológicos', 'Faro', 919999999, 'produtos_biologicos@example.com'
EXEC inserir_cliente 'Farmacêutica Vital', 'Viseu', 961111111, 'farmaceutica_vital@example.com'
EXEC inserir_cliente 'Saúde & Bem-Estar', 'Évora', 962222222, 'sbemestar@example.com'
EXEC inserir_cliente 'Nutrição Completa', 'Setúbal', 969999999, 'nutricao_completa@example.com'
EXEC inserir_cliente 'Herbal Vida', 'Portimão', 969696969, 'herbal_vida@example.com'
EXEC inserir_cliente 'Nutrição Inteligente', 'Leiria', 964444444, 'nutricao_inteligente@example.com'
EXEC inserir_cliente 'Remédios Naturais', 'Loulé', 920000000, 'remedios_naturais@example.com'
EXEC inserir_cliente 'MediFarma', 'Funchal', 968888888, 'medifarma@example.com'
EXEC inserir_cliente 'Frutas e Saúde', 'Barreiro', 915555555, 'frutasesaude@example.com'
EXEC inserir_cliente 'Green Foods', 'Almada', 967777777, 'greenfoods@example.com'
EXEC inserir_cliente 'FarmaVida', 'Cascais', 918888888, 'farmavida@example.com'
EXEC inserir_cliente 'Alimentação Natural', 'Guimarães', 961212121, 'alimentacao_natural@example.com'
EXEC inserir_cliente 'FarmaBio', 'Santarém', 966060606, 'farmabio@example.com'
EXEC inserir_cliente 'Natureza e Saúde', 'Lagos', 966969696, 'naturezasaude@example.com'
EXEC inserir_cliente 'Nutrição Balanceada', 'Amadora', 962626262, 'nutricaobalanceada@example.com'
EXEC inserir_cliente 'Remédios Alternativos', 'Portalegre', 960000000, 'remedios_alternativos@example.com'
